### ISSUE TITLE
Support and continuity of project

### ISSUE THREAD

**Issue by pawansx-22** [rokuality/rokuality-server#11]
Hello,
At first look, I am quite impressed with rokuality tool. We are already having a framework with appium and selenium tests for a well known tv network and willing to integrate rokuality tests in existing framework for some OTT platforms starting with Roku. But, I am little worried about tool's support in future. It will be helpful for us, if you could tell us about its present uses and future plans.
Thanks,
Pawan

**Comment by baclark774** [comment]
Thanks for your interest in the project! We are dedicated to maintaining and expanding as we currently have several major streaming platforms implementing it for their Roku/XBox testing. Our current roadmap includes things like:
1. Add Javascript and Brightscript language support.
2. Add app installation/handling for AppleTV, FireTV, and AndroidTV.
3. Add tools for getting/cropping image based locators from a device screen to help test case creation.
4. Migrate our live session capabilities from a JFrame to a browser based tool.
5. Integrate Azure Computer Vision as alternative OCR engine to Google Vision. And also implement another free OCR engine as an alterative to the default Tesseract.
6. Improve our documentation.

Additionally we have a cloud service launching in January which will allow users to run their Rokuality tests on our large library of Roku devices and integrate their tests with their build processes. More on this to come!

And we welcome all to get involved and support the Rokuality platform!
