### ISSUE TITLE
get_debug_logs is not capturing entire session

### ISSUE THREAD

**Issue by AntonKostenko** [rokuality/rokuality-server#23]
Running server 1.2.8 with python 1.2.4.

I am having issues getting `get_debug_logs` to output the entire session of device logs.
I have a simple test using a sample roku channel. [link here](https://github.com/rokudev/samples/blob/master/channel%20templates/simple-videoplayer-channel.zip)

The test launches the app, sleeps for 30 seconds and closes the app.
While the app is up I use the roku remote and manually make keypresses. Each keypress is logged in the console. This is to simulate outputting more logs.

I call `get_debug_logs` in the beginning of the test when launching the app. 
I can see that device logging starts in the server event logs and I see that it stops at the end of the test.
[2020_02_20_server_event.log](https://github.com/rokuality/rokuality-server/files/4233478/2020_02_20_server_event.log)

This is the roku debug logs I get: [192.168.2.2_roku_debug.log](https://github.com/rokuality/rokuality-server/files/4233485/192.168.2.2_roku_debug.log)

If I perform the same test and enable telnet through a terminal I get the full log output which looks like this. [expected_log_capured_via_telnet.log](https://github.com/rokuality/rokuality-server/files/4233496/expected_log_capured_via_telnet.log)

To me it looks like when calling `get_debug_logs` it dumps what is in memory and does not continue to collect logs.

**Comment by baclark774** [comment]
Thanks for the bug report @AntonKostenko This came up earlier this week in one of the other language bindings. An issue with the back end telnet spywatcher that is being used. We have a fix in place that we're testing out currently and hope to release within the next day or two. Will update as soon as it's available.

**Comment by baclark774** [comment]
@AntonKostenko  Can you try the following build of the server and let me know if this resolves your issue?

https://rokualitypublic.s3.amazonaws.com/rokuality-server-1.2.9-DEBUG.jar

**Comment by AntonKostenko** [comment]
@baclark774 Thank you for the quick feedback.Using the build linked above I am not seeing a debug log file being generated at all in the temp folder.

**Comment by baclark774** [comment]
@AntonKostenko in this build you won't see a physical log file for the roku output. Now the roku telnet stream is captured and saved entirely in the server memory and only retrieved when the user calls the get_debug_logs method. Should be much more efficient this way (in addition to solving the underlying stream capture issues).

**Comment by AntonKostenko** [comment]
Ah I see. That makes a lot of sense. Calling the method gets the entire log output. Thank you.
